// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startRecording: (micDeviceName: string | null, systemDeviceName: string | null, meetingName: string | null) => typedError<null, string>(__TAURI_INVOKE("start_recording", { micDeviceName, systemDeviceName, meetingName })),
	stopRecording: (args: RecordingArgs) => typedError<null, string>(__TAURI_INVOKE("stop_recording", { args })),
	isRecording: () => __TAURI_INVOKE<boolean>("is_recording"),
	getTranscriptionStatus: () => __TAURI_INVOKE<TranscriptionStatus>("get_transcription_status"),
	/**  Whether auto-detection of meeting apps is enabled. */
	getAutoDetectMeetings: () => typedError<boolean, string>(__TAURI_INVOKE("get_auto_detect_meetings")),
	/**
	 *  Enable or disable meeting auto-detection, starting or stopping the foreground
	 *  watcher accordingly.
	 */
	setAutoDetectMeetings: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_auto_detect_meetings", { enabled })),
	/**  Whether both diarization models are present on disk. */
	diarizationModelsReady: () => typedError<boolean, string>(__TAURI_INVOKE("diarization_models_ready")),
	/**
	 *  Diarize a saved meeting: decode its audio, run the sidecar, reconcile speaker
	 *  turns onto the transcript segments, and persist `speaker_id`. Returns the
	 *  number of segments that received a speaker label.
	 */
	diarizeMeeting: (meetingId: string) => typedError<number, string>(__TAURI_INVOKE("diarize_meeting", { meetingId })),
	/**
	 *  Download the diarization models on demand, emitting
	 *  `diarization-model-download-progress`/`-complete`/`-error` events (mirroring
	 *  the Parakeet model-download flow).
	 */
	downloadDiarizationModels: () => typedError<null, string>(__TAURI_INVOKE("download_diarization_models")),
	readAudioFile: (filePath: string) => typedError<number[], string>(__TAURI_INVOKE("read_audio_file", { filePath })),
	saveTranscript: (filePath: string, content: string) => typedError<null, string>(__TAURI_INVOKE("save_transcript", { filePath, content })),
	initAnalytics: () => typedError<null, string>(__TAURI_INVOKE("init_analytics")),
	disableAnalytics: () => typedError<null, string>(__TAURI_INVOKE("disable_analytics")),
	trackEvent: (eventName: string, properties: { [key in string]: string } | null) => typedError<null, string>(__TAURI_INVOKE("track_event", { eventName, properties })),
	identifyUser: (userId: string, properties: { [key in string]: string } | null) => typedError<null, string>(__TAURI_INVOKE("identify_user", { userId, properties })),
	trackMeetingDeleted: (meetingId: string) => typedError<null, string>(__TAURI_INVOKE("track_meeting_deleted", { meetingId })),
	trackSettingsChanged: (settingType: string, newValue: string) => typedError<null, string>(__TAURI_INVOKE("track_settings_changed", { settingType, newValue })),
	trackFeatureUsed: (featureName: string) => typedError<null, string>(__TAURI_INVOKE("track_feature_used", { featureName })),
	isAnalyticsEnabled: () => __TAURI_INVOKE<boolean>("is_analytics_enabled"),
	startAnalyticsSession: (userId: string) => typedError<string, string>(__TAURI_INVOKE("start_analytics_session", { userId })),
	endAnalyticsSession: () => typedError<null, string>(__TAURI_INVOKE("end_analytics_session")),
	trackDailyActiveUser: () => typedError<null, string>(__TAURI_INVOKE("track_daily_active_user")),
	trackUserFirstLaunch: () => typedError<null, string>(__TAURI_INVOKE("track_user_first_launch")),
	isAnalyticsSessionActive: () => __TAURI_INVOKE<boolean>("is_analytics_session_active"),
	trackSummaryGenerationCompleted: (modelProvider: string, modelName: string, success: boolean, durationSeconds: number | null, errorMessage: string | null) => typedError<null, string>(__TAURI_INVOKE("track_summary_generation_completed", { modelProvider, modelName, success, durationSeconds, errorMessage })),
	trackSummaryRegenerated: (modelProvider: string, modelName: string) => typedError<null, string>(__TAURI_INVOKE("track_summary_regenerated", { modelProvider, modelName })),
	trackModelChanged: (oldProvider: string, oldModel: string, newProvider: string, newModel: string) => typedError<null, string>(__TAURI_INVOKE("track_model_changed", { oldProvider, oldModel, newProvider, newModel })),
	trackCustomPromptUsed: (promptLength: number) => typedError<null, string>(__TAURI_INVOKE("track_custom_prompt_used", { promptLength })),
	trackMeetingEnded: (metrics: MeetingEndedMetrics) => typedError<null, string>(__TAURI_INVOKE("track_meeting_ended", { metrics })),
	trackAnalyticsEnabled: () => typedError<null, string>(__TAURI_INVOKE("track_analytics_enabled")),
	trackAnalyticsDisabled: () => typedError<null, string>(__TAURI_INVOKE("track_analytics_disabled")),
	trackAnalyticsTransparencyViewed: () => typedError<null, string>(__TAURI_INVOKE("track_analytics_transparency_viewed")),
	trackException: (report: ExceptionReport) => typedError<null, string>(__TAURI_INVOKE("track_exception", { report })),
	whisperInit: () => typedError<null, string>(__TAURI_INVOKE("whisper_init")),
	whisperGetAvailableModels: () => typedError<WhisperModelInfo[], string>(__TAURI_INVOKE("whisper_get_available_models")),
	whisperLoadModel: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("whisper_load_model", { modelName })),
	whisperGetCurrentModel: () => typedError<string | null, string>(__TAURI_INVOKE("whisper_get_current_model")),
	whisperIsModelLoaded: () => typedError<boolean, string>(__TAURI_INVOKE("whisper_is_model_loaded")),
	whisperHasAvailableModels: () => typedError<boolean, string>(__TAURI_INVOKE("whisper_has_available_models")),
	whisperValidateModelReady: () => typedError<string, string>(__TAURI_INVOKE("whisper_validate_model_ready")),
	whisperTranscribeAudio: (audioData: (number | null)[]) => typedError<string, string>(__TAURI_INVOKE("whisper_transcribe_audio", { audioData })),
	whisperGetModelsDirectory: () => typedError<string, string>(__TAURI_INVOKE("whisper_get_models_directory")),
	whisperDownloadModel: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("whisper_download_model", { modelName })),
	whisperCancelDownload: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("whisper_cancel_download", { modelName })),
	whisperDeleteCorruptedModel: (modelName: string) => typedError<string, string>(__TAURI_INVOKE("whisper_delete_corrupted_model", { modelName })),
	parakeetInit: () => typedError<null, string>(__TAURI_INVOKE("parakeet_init")),
	parakeetGetAvailableModels: () => typedError<ParakeetModelInfo[], string>(__TAURI_INVOKE("parakeet_get_available_models")),
	parakeetLoadModel: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("parakeet_load_model", { modelName })),
	parakeetGetCurrentModel: () => typedError<string | null, string>(__TAURI_INVOKE("parakeet_get_current_model")),
	parakeetIsModelLoaded: () => typedError<boolean, string>(__TAURI_INVOKE("parakeet_is_model_loaded")),
	parakeetHasAvailableModels: () => typedError<boolean, string>(__TAURI_INVOKE("parakeet_has_available_models")),
	parakeetValidateModelReady: () => typedError<string, string>(__TAURI_INVOKE("parakeet_validate_model_ready")),
	parakeetTranscribeAudio: (audioData: (number | null)[]) => typedError<string, string>(__TAURI_INVOKE("parakeet_transcribe_audio", { audioData })),
	parakeetGetModelsDirectory: () => typedError<string, string>(__TAURI_INVOKE("parakeet_get_models_directory")),
	parakeetDownloadModel: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("parakeet_download_model", { modelName })),
	parakeetRetryDownload: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("parakeet_retry_download", { modelName })),
	parakeetCancelDownload: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("parakeet_cancel_download", { modelName })),
	parakeetDeleteCorruptedModel: (modelName: string) => typedError<string, string>(__TAURI_INVOKE("parakeet_delete_corrupted_model", { modelName })),
	/**  Open the Parakeet models folder in the system file explorer */
	openParakeetModelsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_parakeet_models_folder")),
	getAudioDevices: () => typedError<AudioDevice[], string>(__TAURI_INVOKE("get_audio_devices")),
	triggerMicrophonePermission: () => typedError<boolean, string>(__TAURI_INVOKE("trigger_microphone_permission")),
	startRecordingWithDevices: (micDeviceName: string | null, systemDeviceName: string | null) => typedError<null, string>(__TAURI_INVOKE("start_recording_with_devices", { micDeviceName, systemDeviceName })),
	startRecordingWithDevicesAndMeeting: (micDeviceName: string | null, systemDeviceName: string | null, meetingName: string | null) => typedError<null, string>(__TAURI_INVOKE("start_recording_with_devices_and_meeting", { micDeviceName, systemDeviceName, meetingName })),
	startAudioLevelMonitoring: (deviceNames: string[]) => typedError<null, string>(__TAURI_INVOKE("start_audio_level_monitoring", { deviceNames })),
	stopAudioLevelMonitoring: () => typedError<null, string>(__TAURI_INVOKE("stop_audio_level_monitoring")),
	isAudioLevelMonitoring: () => __TAURI_INVOKE<boolean>("is_audio_level_monitoring"),
	/**  Pause the current recording */
	pauseRecording: () => typedError<null, string>(__TAURI_INVOKE("pause_recording")),
	/**  Resume the current recording */
	resumeRecording: () => typedError<null, string>(__TAURI_INVOKE("resume_recording")),
	/**  Check if recording is currently paused */
	isRecordingPaused: () => __TAURI_INVOKE<boolean>("is_recording_paused"),
	/**  Get detailed recording state */
	getRecordingState: () => __TAURI_INVOKE<any>("get_recording_state"),
	/**
	 *  Get the meeting folder path for the current recording
	 *  Returns the path if a meeting name was set and folder structure initialized
	 */
	getMeetingFolderPath: () => typedError<string | null, string>(__TAURI_INVOKE("get_meeting_folder_path")),
	/**
	 *  Get accumulated transcript segments from current recording session
	 *  Used for syncing frontend state after page reload during active recording
	 */
	getTranscriptHistory: () => typedError<TranscriptSegment[], string>(__TAURI_INVOKE("get_transcript_history")),
	/**
	 *  Get meeting name from current recording session
	 *  Used for syncing frontend state after page reload during active recording
	 */
	getRecordingMeetingName: () => typedError<string | null, string>(__TAURI_INVOKE("get_recording_meeting_name")),
	/**
	 *  Poll for audio device events (disconnect/reconnect)
	 *  Should be called periodically (every 1-2 seconds) by frontend during recording
	 */
	pollAudioDeviceEvents: () => typedError<{ type: "DeviceDisconnected"; device_name: string; device_type: string } | { type: "DeviceReconnected"; device_name: string; device_type: string } | { type: "DeviceListChanged" } | null, string>(__TAURI_INVOKE("poll_audio_device_events")),
	/**
	 *  Get current reconnection status
	 *  Returns whether the system is attempting to reconnect and which device
	 */
	getReconnectionStatus: () => typedError<ReconnectionStatus, string>(__TAURI_INVOKE("get_reconnection_status")),
	/**
	 *  Manually trigger device reconnection attempt
	 *  Useful for UI "Retry" button
	 */
	attemptDeviceReconnect: (deviceName: string, deviceType: string) => typedError<boolean, string>(__TAURI_INVOKE("attempt_device_reconnect", { deviceName, deviceType })),
	/**
	 *  Get information about the active audio output device
	 *  Used to warn users about Bluetooth playback issues
	 */
	getActiveAudioOutput: () => typedError<AudioOutputInfo, string>(__TAURI_INVOKE("get_active_audio_output")),
	/**
	 *  Enable or disable the dictation feature. While enabled the transcription
	 *  model is kept warm so a push-to-talk burst doesn't pay a cold reload.
	 */
	setDictationEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_dictation_enabled", { enabled })),
	/**  Whether the dictation feature is currently enabled. */
	getDictationEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("get_dictation_enabled")),
	/**
	 *  Start a push-to-talk dictation burst (mic-only). Rejected while a meeting is
	 *  recording or a dictation burst is already active.
	 */
	startDictation: () => typedError<null, string>(__TAURI_INVOKE("start_dictation")),
	/**  Stop the dictation burst, transcribe it, and return (and emit) the text. */
	stopDictation: () => typedError<string, string>(__TAURI_INVOKE("stop_dictation")),
	/**
	 *  Whether the OS will accept synthesized text injection (Accessibility on macOS).
	 *  The frontend uses this to prompt the user to grant permission.
	 */
	dictationAccessibilityTrusted: () => typedError<boolean, string>(__TAURI_INVOKE("dictation_accessibility_trusted")),
	/**  Whether local-AI cleanup of dictated text is enabled. */
	getDictationCleanupEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("get_dictation_cleanup_enabled")),
	/**  Enable or disable local-AI cleanup of dictated text. */
	setDictationCleanupEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_dictation_cleanup_enabled", { enabled })),
	/**  List all dictation cleanup presets, oldest first. */
	listDictationCleanupPresets: () => typedError<DictationCleanupPreset[], string>(__TAURI_INVOKE("list_dictation_cleanup_presets")),
	/**  Create a new (inactive) cleanup preset and return it. */
	createDictationCleanupPreset: (name: string, prompt: string) => typedError<DictationCleanupPreset, string>(__TAURI_INVOKE("create_dictation_cleanup_preset", { name, prompt })),
	/**  Update a cleanup preset's name and prompt. */
	updateDictationCleanupPreset: (id: string, name: string, prompt: string) => typedError<null, string>(__TAURI_INVOKE("update_dictation_cleanup_preset", { id, name, prompt })),
	/**  Delete a cleanup preset. */
	deleteDictationCleanupPreset: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_dictation_cleanup_preset", { id })),
	/**  Make a cleanup preset the active one (clears the others). */
	setActiveDictationCleanupPreset: (id: string) => typedError<null, string>(__TAURI_INVOKE("set_active_dictation_cleanup_preset", { id })),
	/**
	 *  Recover audio from checkpoint files
	 *  This is called by the transcript recovery system to merge audio chunks after a crash
	 */
	recoverAudioFromCheckpoints: (meetingFolder: string, sampleRate: number) => typedError<AudioRecoveryStatus, string>(__TAURI_INVOKE("recover_audio_from_checkpoints", { meetingFolder, sampleRate })),
	/**
	 *  Clean up checkpoint files after successful recording or recovery
	 *  This command is called by the frontend after successful save to clean up checkpoint files
	 */
	cleanupCheckpoints: (meetingFolder: string) => typedError<null, string>(__TAURI_INVOKE("cleanup_checkpoints", { meetingFolder })),
	/**
	 *  Check if a meeting folder has audio checkpoint files
	 *  Returns true if .checkpoints/ directory exists and contains .mp4 files
	 */
	hasAudioCheckpoints: (meetingFolder: string) => typedError<boolean, string>(__TAURI_INVOKE("has_audio_checkpoints", { meetingFolder })),
	showConsole: () => typedError<string, string>(__TAURI_INVOKE("show_console")),
	hideConsole: () => typedError<string, string>(__TAURI_INVOKE("hide_console")),
	toggleConsole: () => typedError<string, string>(__TAURI_INVOKE("toggle_console")),
	getOllamaModels: (endpoint: string | null) => typedError<OllamaModel[], string>(__TAURI_INVOKE("get_ollama_models", { endpoint })),
	pullOllamaModel: (modelName: string, endpoint: string | null) => typedError<null, string>(__TAURI_INVOKE("pull_ollama_model", { modelName, endpoint })),
	deleteOllamaModel: (modelName: string, endpoint: string | null) => typedError<null, string>(__TAURI_INVOKE("delete_ollama_model", { modelName, endpoint })),
	/**
	 *  Get the context size for a specific Ollama model
	 * 
	 *  This command fetches model metadata and returns the context size.
	 *  Results are cached for 5 minutes to avoid repeated API calls.
	 * 
	 *  # Arguments
	 *  * `model_name` - Name of the model (e.g., "llama3.2:1b")
	 *  * `endpoint` - Optional custom Ollama endpoint
	 * 
	 *  # Returns
	 *  Context size in tokens, or error message
	 */
	getOllamaModelContext: (modelName: string, endpoint: string | null) => typedError<number, string>(__TAURI_INVOKE("get_ollama_model_context", { modelName, endpoint })),
	/**  Fetch OpenAI models from the API (falls back to a hardcoded list on error). */
	getOpenaiModels: (apiKey: string | null) => typedError<OpenAIModel[], string>(__TAURI_INVOKE("get_openai_models", { apiKey })),
	/**  Fetch Anthropic models from the API (falls back to a hardcoded list on error). */
	getAnthropicModels: (apiKey: string | null) => typedError<AnthropicModel[], string>(__TAURI_INVOKE("get_anthropic_models", { apiKey })),
	/**  Fetch Groq models from the API (falls back to a hardcoded list on error). */
	getGroqModels: (apiKey: string | null) => typedError<GroqModel[], string>(__TAURI_INVOKE("get_groq_models", { apiKey })),
	/**  Fetch xAI models from the API (falls back to a hardcoded list on error). */
	getXaiModels: (apiKey: string | null) => typedError<XaiModel[], string>(__TAURI_INVOKE("get_xai_models", { apiKey })),
	apiGetMeetings: (authToken: string | null, page: number | null, pageSize: number | null) => typedError<Meeting_Serialize[], string>(__TAURI_INVOKE("api_get_meetings", { authToken, page, pageSize })),
	apiSearchTranscripts: (query: string, authToken: string | null) => typedError<TranscriptSearchResult[], string>(__TAURI_INVOKE("api_search_transcripts", { query, authToken })),
	apiGetModelConfig: (authToken: string | null) => typedError<{
	provider: string,
	model: string,
	whisperModel: string,
	apiKey: string | null,
	ollamaEndpoint: string | null,
} | null, string>(__TAURI_INVOKE("api_get_model_config", { authToken })),
	apiSaveModelConfig: (provider: string, model: string, whisperModel: string, apiKey: string | null, ollamaEndpoint: string | null, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_save_model_config", { provider, model, whisperModel, apiKey, ollamaEndpoint, authToken })),
	apiGetApiKey: (provider: string, authToken: string | null) => typedError<string, string>(__TAURI_INVOKE("api_get_api_key", { provider, authToken })),
	apiGetTranscriptConfig: (authToken: string | null) => typedError<{
	provider: string,
	model: string,
	apiKey: string | null,
} | null, string>(__TAURI_INVOKE("api_get_transcript_config", { authToken })),
	apiSaveTranscriptConfig: (provider: string, model: string, apiKey: string | null, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_save_transcript_config", { provider, model, apiKey, authToken })),
	apiGetTranscriptApiKey: (provider: string, authToken: string | null) => typedError<string, string>(__TAURI_INVOKE("api_get_transcript_api_key", { provider, authToken })),
	apiDeleteMeeting: (meetingId: string, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_delete_meeting", { meetingId, authToken })),
	/**  List meetings currently in the trash (soft-deleted, restorable). */
	apiGetTrashedMeetings: (authToken: string | null) => typedError<Meeting_Serialize[], string>(__TAURI_INVOKE("api_get_trashed_meetings", { authToken })),
	/**  Restore a meeting from the trash back to the active list. */
	apiRestoreMeeting: (meetingId: string, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_restore_meeting", { meetingId, authToken })),
	/**  Permanently delete a meeting and all its data (used from the Trash view). */
	apiPermanentlyDeleteMeeting: (meetingId: string, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_permanently_delete_meeting", { meetingId, authToken })),
	apiListFolders: () => typedError<Folder[], string>(__TAURI_INVOKE("api_list_folders")),
	apiCreateFolder: (name: string, emoji: string | null) => typedError<Folder, string>(__TAURI_INVOKE("api_create_folder", { name, emoji })),
	apiUpdateFolder: (folderId: string, name: string, emoji: string | null) => typedError<any, string>(__TAURI_INVOKE("api_update_folder", { folderId, name, emoji })),
	apiDeleteFolder: (folderId: string) => typedError<any, string>(__TAURI_INVOKE("api_delete_folder", { folderId })),
	/**  Move a meeting into a folder, or out of all folders when `folder_id` is None. */
	apiMoveMeetingToFolder: (meetingId: string, folderId: string | null) => typedError<any, string>(__TAURI_INVOKE("api_move_meeting_to_folder", { meetingId, folderId })),
	apiGetMeeting: (meetingId: string, authToken: string | null) => typedError<MeetingDetails_Serialize, string>(__TAURI_INVOKE("api_get_meeting", { meetingId, authToken })),
	/**  Get meeting metadata without transcripts (for pagination) */
	apiGetMeetingMetadata: (meetingId: string) => typedError<MeetingMetadata_Serialize, string>(__TAURI_INVOKE("api_get_meeting_metadata", { meetingId })),
	/**  Get paginated transcripts for a meeting */
	apiGetMeetingTranscripts: (meetingId: string, limit: number, offset: number) => typedError<PaginatedTranscriptsResponse_Serialize, string>(__TAURI_INVOKE("api_get_meeting_transcripts", { meetingId, limit, offset })),
	apiSaveMeetingTitle: (meetingId: string, title: string, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_save_meeting_title", { meetingId, title, authToken })),
	/**  Persist the user's in-meeting notes (markdown) for a meeting. */
	apiSaveMeetingNotes: (meetingId: string, notesMarkdown: string, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_save_meeting_notes", { meetingId, notesMarkdown, authToken })),
	/**
	 *  Load the user's saved notes for a meeting, plus the per-meeting summary
	 *  context. Both live on the same `meeting_notes` row, so a single read returns
	 *  them together; each field is empty when nothing has been saved yet.
	 */
	apiGetMeetingNotes: (meetingId: string, authToken: string | null) => typedError<NotesResponse_Serialize, string>(__TAURI_INVOKE("api_get_meeting_notes", { meetingId, authToken })),
	/**
	 *  Persist the per-meeting context the user types to steer AI summary
	 *  generation. Stored alongside notes on the `meeting_notes` row.
	 */
	apiSaveMeetingSummaryContext: (meetingId: string, summaryContext: string, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_save_meeting_summary_context", { meetingId, summaryContext, authToken })),
	/**
	 *  Export a meeting's note as a Markdown file. Opens a native Save dialog and
	 *  writes the provided markdown to the chosen path. Returns the saved path, or
	 *  `None` if the user cancelled. The frontend builds the markdown (title +
	 *  summary) so this stays a thin save helper.
	 */
	apiExportMeetingMarkdown: (defaultFileName: string, contents: string, authToken: string | null) => typedError<string | null, string>(__TAURI_INVOKE("api_export_meeting_markdown", { defaultFileName, contents, authToken })),
	apiSaveTranscript: (meetingTitle: string, transcripts: any[], folderPath: string | null, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_save_transcript", { meetingTitle, transcripts, folderPath, authToken })),
	/**  Opens the meeting's recording folder in the system file explorer */
	openMeetingFolder: (meetingId: string) => typedError<null, string>(__TAURI_INVOKE("open_meeting_folder", { meetingId })),
	openExternalUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_external_url", { url })),
	/**
	 *  Saves the custom OpenAI configuration
	 *  This configuration is stored as JSON and includes endpoint, apiKey, model, and optional parameters
	 */
	apiSaveCustomOpenaiConfig: (endpoint: string, apiKey: string | null, model: string, maxTokens: number | null, temperature: number | null, topP: number | null) => typedError<any, string>(__TAURI_INVOKE("api_save_custom_openai_config", { endpoint, apiKey, model, maxTokens, temperature, topP })),
	/**  Gets the custom OpenAI configuration */
	apiGetCustomOpenaiConfig: () => typedError<{
	/**  Base URL of the OpenAI-compatible API endpoint (e.g., "http://localhost:8000/v1") */
	endpoint: string,
	/**  API key for authentication (optional if server doesn't require it) */
	apiKey: string | null,
	/**  Model identifier to use (e.g., "gpt-4", "llama-3-70b", "mistral-7b") */
	model: string,
	/**  Maximum tokens for completion (optional) */
	maxTokens: number | null,
	/**  Temperature parameter (0.0-2.0, optional) */
	temperature: number | null,
	/**  Top-P sampling parameter (0.0-1.0, optional) */
	topP: number | null,
} | null, string>(__TAURI_INVOKE("api_get_custom_openai_config")),
	/**
	 *  Tests the connection to a custom OpenAI-compatible endpoint
	 *  Makes a minimal request to verify the endpoint is reachable and responds correctly
	 */
	apiTestCustomOpenaiConnection: (endpoint: string, apiKey: string | null, model: string) => typedError<any, string>(__TAURI_INVOKE("api_test_custom_openai_connection", { endpoint, apiKey, model })),
	apiProcessTranscript: (params: ProcessTranscriptParams) => typedError<ProcessTranscriptResponse, string>(__TAURI_INVOKE("api_process_transcript", { params })),
	/**
	 *  Gets summary status and data (Native SQLx implementation)
	 * 
	 *  Returns summary status (pending/processing/completed/failed) and parsed result data
	 */
	apiGetSummary: (meetingId: string, authToken: string | null) => typedError<SummaryResponse, string>(__TAURI_INVOKE("api_get_summary", { meetingId, authToken })),
	/**
	 *  Saves a meeting summary (Native SQLx implementation)
	 * 
	 *  Expected format: { "markdown": "...", "summary_json": [...BlockNote blocks...] }
	 */
	apiSaveMeetingSummary: (meetingId: string, summary: any, authToken: string | null) => typedError<any, string>(__TAURI_INVOKE("api_save_meeting_summary", { meetingId, summary, authToken })),
	/**
	 *  Cancels an ongoing summary generation process
	 * 
	 *  This command triggers the cancellation token for the specified meeting,
	 *  stopping the summary generation gracefully.
	 */
	apiCancelSummary: (meetingId: string) => typedError<any, string>(__TAURI_INVOKE("api_cancel_summary", { meetingId })),
	/**
	 *  Gets the per-meeting summary output language override from metadata.json.
	 *  Returns None when no override is set or the meeting has no folder yet (the
	 *  frontend then falls back to its own default preference).
	 */
	apiGetMeetingSummaryLanguage: (meetingId: string) => typedError<string | null, string>(__TAURI_INVOKE("api_get_meeting_summary_language", { meetingId })),
	/**  Saves or clears the per-meeting summary output language override. */
	apiSaveMeetingSummaryLanguage: (meetingId: string, summaryLanguage: string | null) => typedError<string | null, string>(__TAURI_INVOKE("api_save_meeting_summary_language", { meetingId, summaryLanguage })),
	/**  Gets the cached auto-detected transcript summary language from metadata.json. */
	apiGetMeetingDetectedSummaryLanguage: (meetingId: string) => typedError<string | null, string>(__TAURI_INVOKE("api_get_meeting_detected_summary_language", { meetingId })),
	/**  Detects the dominant supported summary language from transcript segments. */
	apiDetectTranscriptSummaryLanguage: (transcriptTexts: string[]) => typedError<SummaryLanguageDetection, string>(__TAURI_INVOKE("api_detect_transcript_summary_language", { transcriptTexts })),
	/**
	 *  Generates and persists a concise meeting title from the transcript using the
	 *  configured model. Lightweight and independent of full summary generation, so
	 *  a meeting gets a real title automatically once it ends.
	 */
	apiGenerateMeetingTitle: (meetingId: string, text: string, model: string, modelName: string) => typedError<string, string>(__TAURI_INVOKE("api_generate_meeting_title", { meetingId, text, model, modelName })),
	/**
	 *  Lists all available templates
	 * 
	 *  Returns templates from both built-in (embedded) and custom (user data directory) sources.
	 *  Templates are automatically discovered - no code changes needed to add new templates.
	 * 
	 *  # Returns
	 *  Vector of TemplateInfo with id, name, and description for each template
	 */
	apiListTemplates: () => typedError<TemplateInfo[], string>(__TAURI_INVOKE("api_list_templates")),
	/**
	 *  Gets detailed information about a specific template
	 * 
	 *  # Arguments
	 *  * `template_id` - Template identifier (e.g., "daily_standup")
	 * 
	 *  # Returns
	 *  TemplateDetails with full template structure
	 */
	apiGetTemplateDetails: (templateId: string) => typedError<TemplateDetails, string>(__TAURI_INVOKE("api_get_template_details", { templateId })),
	/**
	 *  Validates a custom template JSON string
	 * 
	 *  Useful for template editor UI or validation before saving custom templates
	 * 
	 *  # Arguments
	 *  * `template_json` - Raw JSON string of the template
	 * 
	 *  # Returns
	 *  Ok(template_name) if valid, Err(error_message) if invalid
	 */
	apiValidateTemplate: (templateJson: string) => typedError<string, string>(__TAURI_INVOKE("api_validate_template", { templateJson })),
	/**  List all available built-in AI models with their status */
	builtinAiListModels: () => typedError<SummaryModelInfo[], string>(__TAURI_INVOKE("builtin_ai_list_models")),
	/**  Get information about a specific model */
	builtinAiGetModelInfo: (modelName: string) => typedError<{
	/**  Model name (e.g., "gemma3:1b") */
	name: string,
	/**  Display name for UI */
	display_name: string,
	/**  Current status */
	status: any,
	/**  File path (if available) */
	path: string,
	/**  Size in MB */
	size_mb: number,
	/**  Context window size in tokens */
	context_size: number,
	/**  Description */
	description: string,
	/**  GGUF filename on disk */
	gguf_file: string,
} | null, string>(__TAURI_INVOKE("builtin_ai_get_model_info", { modelName })),
	/**  Download a built-in AI model with progress updates */
	builtinAiDownloadModel: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("builtin_ai_download_model", { modelName })),
	/**  Cancel an ongoing model download */
	builtinAiCancelDownload: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("builtin_ai_cancel_download", { modelName })),
	/**  Delete a corrupted or available model file */
	builtinAiDeleteModel: (modelName: string) => typedError<null, string>(__TAURI_INVOKE("builtin_ai_delete_model", { modelName })),
	/**  Check if a model is ready to use */
	builtinAiIsModelReady: (modelName: string, refresh: boolean | null) => typedError<boolean, string>(__TAURI_INVOKE("builtin_ai_is_model_ready", { modelName, refresh })),
	/**
	 *  Check if any summary model is available (for onboarding)
	 *  Returns the first available model name by priority, or None if no models exist
	 */
	builtinAiGetAvailableSummaryModel: () => typedError<string | null, string>(__TAURI_INVOKE("builtin_ai_get_available_summary_model")),
	/**
	 *  Get the recommended summary model for this machine, used to seed the
	 *  onboarding default instead of always falling back to gemma3.
	 * 
	 *  Selection (see [`recommend_summary_model`] for the exact tiers):
	 *  - macOS (Apple Silicon, unified memory): sized by total system RAM.
	 *  - Discrete NVIDIA GPU (VRAM from `nvidia-smi`): sized by VRAM.
	 *  - CPU-only / undetected GPU: conservative RAM-based pick (CPU inference is
	 *    slow, so we never auto-recommend the 8B model there).
	 */
	builtinAiGetRecommendedModel: () => typedError<string, string>(__TAURI_INVOKE("builtin_ai_get_recommended_model")),
	/**
	 *  Fetch the OpenRouter model catalog.
	 * 
	 *  The `/models` endpoint is public (no API key). This is `async` and uses the
	 *  shared HTTP client with a timeout — the previous `reqwest::blocking` client
	 *  would panic ("runtime within a runtime") or stall the executor when called
	 *  from Tauri's async command dispatch.
	 */
	getOpenrouterModels: () => typedError<OpenRouterModel[], string>(__TAURI_INVOKE("get_openrouter_models")),
	/**  Tauri commands for recording preferences */
	getRecordingPreferences: () => typedError<RecordingPreferences, string>(__TAURI_INVOKE("get_recording_preferences")),
	setRecordingPreferences: (preferences: RecordingPreferences) => typedError<null, string>(__TAURI_INVOKE("set_recording_preferences", { preferences })),
	getDefaultRecordingsFolderPath: () => typedError<string, string>(__TAURI_INVOKE("get_default_recordings_folder_path")),
	openRecordingsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_recordings_folder")),
	selectRecordingFolder: () => typedError<string | null, string>(__TAURI_INVOKE("select_recording_folder")),
	/**  Get available audio capture backends for the current platform */
	getAvailableAudioBackends: () => typedError<string[], string>(__TAURI_INVOKE("get_available_audio_backends")),
	/**  Get current audio capture backend */
	getCurrentAudioBackend: () => typedError<string, string>(__TAURI_INVOKE("get_current_audio_backend")),
	/**  Set audio capture backend */
	setAudioBackend: (backend: string) => typedError<null, string>(__TAURI_INVOKE("set_audio_backend", { backend })),
	getAudioBackendInfo: () => typedError<BackendInfo[], string>(__TAURI_INVOKE("get_audio_backend_info")),
	setLanguagePreference: (language: string) => typedError<null, string>(__TAURI_INVOKE("set_language_preference", { language })),
	/**
	 *  Read the persisted transcription language from the DB, or `None` if unset.
	 *  The frontend uses this to treat the DB as the source of truth and to run a
	 *  one-time migration of the legacy localStorage value.
	 */
	getTranscriptionLanguage: () => typedError<string | null, string>(__TAURI_INVOKE("get_transcription_language")),
	setCustomVocabulary: (entries: VocabularyEntry[]) => typedError<null, string>(__TAURI_INVOKE("set_custom_vocabulary", { entries })),
	getCustomVocabulary: () => typedError<VocabularyEntry[], string>(__TAURI_INVOKE("get_custom_vocabulary")),
	setRecordingShortcutEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_recording_shortcut_enabled", { enabled })),
	setDictationShortcutEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_dictation_shortcut_enabled", { enabled })),
	/**  Get notification settings */
	getNotificationSettings: () => typedError<NotificationSettings, string>(__TAURI_INVOKE("get_notification_settings")),
	/**  Set notification settings */
	setNotificationSettings: (settings: NotificationSettings) => typedError<null, string>(__TAURI_INVOKE("set_notification_settings", { settings })),
	/**  Request notification permission from the system */
	requestNotificationPermission: () => typedError<boolean, string>(__TAURI_INVOKE("request_notification_permission")),
	/**  Show a custom notification */
	showNotification: (notification: Notification) => typedError<null, string>(__TAURI_INVOKE("show_notification", { notification })),
	/**  Show a test notification */
	showTestNotification: () => typedError<null, string>(__TAURI_INVOKE("show_test_notification")),
	/**  Check if Do Not Disturb is active */
	isDndActive: () => typedError<boolean, string>(__TAURI_INVOKE("is_dnd_active")),
	/**  Get system Do Not Disturb status */
	getSystemDndStatus: () => typedError<boolean, string>(__TAURI_INVOKE("get_system_dnd_status")),
	/**  Set manual Do Not Disturb mode */
	setManualDnd: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_manual_dnd", { enabled })),
	/**  Set user consent for notifications */
	setNotificationConsent: (consent: boolean) => typedError<null, string>(__TAURI_INVOKE("set_notification_consent", { consent })),
	/**  Clear all notifications */
	clearNotifications: () => typedError<null, string>(__TAURI_INVOKE("clear_notifications")),
	/**  Check if notification system is ready */
	isNotificationSystemReady: () => typedError<boolean, string>(__TAURI_INVOKE("is_notification_system_ready")),
	/**  Initialize notification manager manually (for testing and ensuring it's ready) */
	initializeNotificationManagerManual: () => typedError<null, string>(__TAURI_INVOKE("initialize_notification_manager_manual")),
	/**  Test notification with automatic consent for development/testing */
	testNotificationWithAutoConsent: () => typedError<null, string>(__TAURI_INVOKE("test_notification_with_auto_consent")),
	/**  Get notification system statistics */
	getNotificationStats: () => typedError<any, string>(__TAURI_INVOKE("get_notification_stats")),
	/**  Start system audio capture (for capturing system output audio) */
	startSystemAudioCaptureCommand: () => typedError<string, string>(__TAURI_INVOKE("start_system_audio_capture_command")),
	/**  List available system audio devices */
	listSystemAudioDevicesCommand: () => typedError<string[], string>(__TAURI_INVOKE("list_system_audio_devices_command")),
	/**  Check if the app has permission to access system audio */
	checkSystemAudioPermissionsCommand: () => __TAURI_INVOKE<boolean>("check_system_audio_permissions_command"),
	/**  Start monitoring system audio usage by other applications */
	startSystemAudioMonitoring: () => typedError<null, string>(__TAURI_INVOKE("start_system_audio_monitoring")),
	/**  Stop monitoring system audio usage */
	stopSystemAudioMonitoring: () => typedError<null, string>(__TAURI_INVOKE("stop_system_audio_monitoring")),
	/**  Get the current status of system audio monitoring */
	getSystemAudioMonitoringStatus: () => typedError<boolean, string>(__TAURI_INVOKE("get_system_audio_monitoring_status")),
	/**  Tauri command to check Screen Recording permission */
	checkScreenRecordingPermissionCommand: () => __TAURI_INVOKE<boolean>("check_screen_recording_permission_command"),
	/**  Tauri command to request Screen Recording permission */
	requestScreenRecordingPermissionCommand: () => typedError<null, string>(__TAURI_INVOKE("request_screen_recording_permission_command")),
	/**
	 *  Tauri command to trigger system audio permission request
	 *  Returns true if permission was granted (stream created), false if denied
	 */
	triggerSystemAudioPermissionCommand: () => typedError<boolean, string>(__TAURI_INVOKE("trigger_system_audio_permission_command")),
	/**
	 *  Tauri command: query the System Audio Recording permission status without
	 *  triggering any prompt. Returns "granted" | "denied" | "undetermined" | "unknown".
	 */
	checkSystemAudioPermissionCommand: () => __TAURI_INVOKE<string>("check_system_audio_permission_command"),
	/**  Check if this is the first launch (no database exists yet) */
	checkFirstLaunch: () => typedError<boolean, string>(__TAURI_INVOKE("check_first_launch")),
	/**  Open a dialog to select a folder or file for legacy database import */
	selectLegacyDatabasePath: () => typedError<string | null, string>(__TAURI_INVOKE("select_legacy_database_path")),
	/**  Detect legacy database from a selected path (root repo, backend folder, or db file) */
	detectLegacyDatabase: (selectedPath: string) => typedError<string | null, string>(__TAURI_INVOKE("detect_legacy_database", { selectedPath })),
	/**  Check for legacy database in the default app data directory */
	checkDefaultLegacyDatabase: () => typedError<string | null, string>(__TAURI_INVOKE("check_default_legacy_database")),
	/**
	 *  Check if the Homebrew database exists and return its size
	 *  This is specifically for detecting old Python backend installations
	 */
	checkHomebrewDatabase: (path: string) => typedError<{
	exists: boolean,
	size: number,
} | null, string>(__TAURI_INVOKE("check_homebrew_database", { path })),
	/**  Import legacy database and initialize the database manager */
	importAndInitializeDatabase: (legacyDbPath: string) => typedError<null, string>(__TAURI_INVOKE("import_and_initialize_database", { legacyDbPath })),
	/**  Initialize a fresh database (for users who don't want to import) */
	initializeFreshDatabase: () => typedError<null, string>(__TAURI_INVOKE("initialize_fresh_database")),
	/**  Get the database directory path */
	getDatabaseDirectory: () => typedError<string, string>(__TAURI_INVOKE("get_database_directory")),
	/**  Open the database folder in the system file explorer */
	openDatabaseFolder: () => typedError<null, string>(__TAURI_INVOKE("open_database_folder")),
	/**  Open the models folder in the system file explorer */
	openModelsFolder: () => typedError<null, string>(__TAURI_INVOKE("open_models_folder")),
	/**  Tauri commands for onboarding status */
	getOnboardingStatus: () => typedError<{
	version: string,
	completed: boolean,
	current_step: number,
	model_status: ModelStatus,
	last_updated: string,
} | null, string>(__TAURI_INVOKE("get_onboarding_status")),
	saveOnboardingStatusCmd: (status: OnboardingStatus) => typedError<null, string>(__TAURI_INVOKE("save_onboarding_status_cmd", { status })),
	resetOnboardingStatusCmd: () => typedError<null, string>(__TAURI_INVOKE("reset_onboarding_status_cmd")),
	completeOnboarding: (model: string) => typedError<null, string>(__TAURI_INVOKE("complete_onboarding", { model })),
	/**  Opens macOS System Settings to a specific privacy preference pane */
	openSystemSettings: (preferencePane: string) => typedError<null, string>(__TAURI_INVOKE("open_system_settings", { preferencePane })),
	startRetranscriptionCommand: (meetingId: string, meetingFolderPath: string, language: string | null, model: string | null, provider: string | null) => typedError<RetranscriptionStarted, string>(__TAURI_INVOKE("start_retranscription_command", { meetingId, meetingFolderPath, language, model, provider })),
	cancelRetranscriptionCommand: () => typedError<null, string>(__TAURI_INVOKE("cancel_retranscription_command")),
	isRetranscriptionInProgressCommand: () => __TAURI_INVOKE<boolean>("is_retranscription_in_progress_command"),
	/**  Select an audio file and validate it */
	selectAndValidateAudioCommand: () => typedError<{
	path: string,
	filename: string,
	duration_seconds: number | null,
	size_bytes: number,
	format: string,
} | null, string>(__TAURI_INVOKE("select_and_validate_audio_command")),
	/**  Validate an audio file from a given path (for drag-drop) */
	validateAudioFileCommand: (path: string) => typedError<AudioFileInfo, string>(__TAURI_INVOKE("validate_audio_file_command", { path })),
	/**  Start importing an audio file (Beta gated using configContext.betaFeatures) */
	startImportAudioCommand: (sourcePath: string, title: string, language: string | null, model: string | null, provider: string | null) => typedError<ImportStarted, string>(__TAURI_INVOKE("start_import_audio_command", { sourcePath, title, language, model, provider })),
	/**  Cancel ongoing import */
	cancelImportCommand: () => typedError<null, string>(__TAURI_INVOKE("cancel_import_command")),
	/**  Check if import is in progress */
	isImportInProgressCommand: () => __TAURI_INVOKE<boolean>("is_import_in_progress_command"),
	calendarPermissionStatus: () => __TAURI_INVOKE<CalendarAuthStatus>("calendar_permission_status"),
	calendarRequestAccess: () => typedError<CalendarAuthStatus, string>(__TAURI_INVOKE("calendar_request_access")),
	calendarOpenSettings: () => typedError<null, string>(__TAURI_INVOKE("calendar_open_settings")),
	calendarListCalendars: () => typedError<CalendarInfo[], string>(__TAURI_INVOKE("calendar_list_calendars")),
	calendarGetContextEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("calendar_get_context_enabled")),
	calendarSetContextEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("calendar_set_context_enabled", { enabled })),
	calendarGetExcludedIds: () => typedError<string[], string>(__TAURI_INVOKE("calendar_get_excluded_ids")),
	calendarSetExcludedIds: (ids: string[]) => typedError<null, string>(__TAURI_INVOKE("calendar_set_excluded_ids", { ids })),
	calendarGetSendAttendeeNamesToCloud: () => typedError<boolean, string>(__TAURI_INVOKE("calendar_get_send_attendee_names_to_cloud")),
	calendarSetSendAttendeeNamesToCloud: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("calendar_set_send_attendee_names_to_cloud", { enabled })),
	calendarGetSendNotesToCloud: () => typedError<boolean, string>(__TAURI_INVOKE("calendar_get_send_notes_to_cloud")),
	calendarSetSendNotesToCloud: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("calendar_set_send_notes_to_cloud", { enabled })),
	/**  Read the calendar snapshot attached to a recording (for the detail view). */
	calendarGetEvent: (meetingId: string) => typedError<{
	meeting_id: string,
	/**  EventKit series identifier (shared across recurring occurrences). */
	event_identifier: string | null,
	/**  Occurrence start (RFC3339) that disambiguates a recurring instance. */
	occurrence_start: string | null,
	title: string | null,
	start_time: string | null,
	end_time: string | null,
	/**  Organizer display name only - never an email address. */
	organizer_name: string | null,
	/**  JSON array of `{name, status}` - names only, never emails. */
	attendees_json: string | null,
	location: string | null,
	conference_url: string | null,
	/**  Event notes/agenda, secret-scrubbed and length-capped before storage. */
	notes: string | null,
	calendar_name: string | null,
	/**  Origin of the snapshot: "eventkit" or "google". */
	source: string,
	/**  Which calendar account won dedup (e.g. "eventkit-local" or a Google sub). */
	account_id: string | null,
	/**  Cross-system event UID (EventKit external id / Google iCalUID). */
	ical_uid: string | null,
	/**  How the event was matched: "high", "low", or "manual". */
	match_confidence: string,
	created_at: string,
} | null, string>(__TAURI_INVOKE("calendar_get_event", { meetingId })),
	/**
	 *  Resolve and attach the calendar event for a recording. Called by the frontend
	 *  after a recording is saved (auto), and on manual re-attach. Resolves for the
	 *  meeting's start instant.
	 */
	calendarAttachEvent: (meetingId: string) => typedError<boolean, string>(__TAURI_INVOKE("calendar_attach_event", { meetingId })),
	/**  Detach the calendar snapshot from a recording. */
	calendarDetachEvent: (meetingId: string) => typedError<null, string>(__TAURI_INVOKE("calendar_detach_event", { meetingId })),
	/**  Delete every stored calendar snapshot (offered when disabling the feature). */
	calendarPurgeAllSnapshots: () => typedError<number, string>(__TAURI_INVOKE("calendar_purge_all_snapshots")),
	/**  Whether a Google OAuth client id is configured (drives the "Add account" UI). */
	calendarGoogleConfigured: () => __TAURI_INVOKE<boolean>("calendar_google_configured"),
	/**  All connected calendar sources (the local source + any Google accounts). */
	calendarListAccounts: () => typedError<CalendarAccount[], string>(__TAURI_INVOKE("calendar_list_accounts")),
	/**  Run the Google OAuth flow (system browser + loopback) and persist the account. */
	calendarAddGoogleAccount: () => typedError<CalendarAccount, string>(__TAURI_INVOKE("calendar_add_google_account")),
	/**
	 *  Remove a Google account: revoke + clear its keychain token, then delete the
	 *  row. Snapshots captured from it are kept (historical). The local source can't
	 *  be removed (toggle it off instead).
	 */
	calendarRemoveAccount: (accountId: string) => typedError<null, string>(__TAURI_INVOKE("calendar_remove_account", { accountId })),
	/**  Enable or disable a single source. */
	calendarSetAccountEnabled: (accountId: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("calendar_set_account_enabled", { accountId, enabled })),
	/**
	 *  One account's calendars for the per-account selection UI. Served from the list
	 *  cached on the account (no network) so opening settings is instant; refreshing
	 *  from Google is an explicit action (`calendar_refresh_account_calendars`). The
	 *  local EventKit source is always read live since it is an on-device call.
	 */
	calendarListAccountCalendars: (accountId: string) => typedError<CalendarInfo[], string>(__TAURI_INVOKE("calendar_list_account_calendars", { accountId })),
	/**
	 *  Pull a fresh calendar list from Google and cache it on the account. This is the
	 *  only path that hits the network for calendars, triggered by the manual refresh.
	 */
	calendarRefreshAccountCalendars: (accountId: string) => typedError<CalendarInfo[], string>(__TAURI_INVOKE("calendar_refresh_account_calendars", { accountId })),
	/**  Set the excluded calendar ids for one account. */
	calendarSetAccountExcludedIds: (accountId: string, ids: string[]) => typedError<null, string>(__TAURI_INVOKE("calendar_set_account_excluded_ids", { accountId, ids })),
	/**  Preview upcoming events across all enabled sources (settings verification). */
	calendarPreviewUpcoming: () => typedError<PreviewEvent[], string>(__TAURI_INVOKE("calendar_preview_upcoming")),
	/**  One-click, secret-free diagnostic for a calendar source (where it fails). */
	calendarDiagnose: (accountId: string) => typedError<string, string>(__TAURI_INVOKE("calendar_diagnose", { accountId })),
};

/* Types */
/**  Anthropic (Claude) model information returned to frontend */
export type AnthropicModel = {
	id: string,
	display_name: string | null,
};

export type AudioDevice = {
	name: string,
	device_type: DeviceType,
};

/**  Information about a selected audio file */
export type AudioFileInfo = {
	path: string,
	filename: string,
	duration_seconds: number | null,
	size_bytes: number,
	format: string,
};

export type AudioOutputInfo = {
	device_name: string,
	is_bluetooth: boolean,
	sample_rate: number | null,
	device_type: string,
};

/**  Audio recovery status for transcript recovery feature */
export type AudioRecoveryStatus = {
	status: string,
	chunk_count: number,
	estimated_duration_seconds: number | null,
	audio_file_path: string | null,
	message: string,
};

/**  Get backend information (name and description) */
export type BackendInfo = {
	id: string,
	name: string,
	description: string,
};

/**
 *  A calendar source the user has connected. The local EventKit source is one
 *  synthetic row ("eventkit-local"); each connected Google account is one row
 *  keyed by its Google `sub`. Refresh tokens live in the keychain, not here.
 */
export type CalendarAccount = {
	/**  Google `sub`, or the sentinel "eventkit-local". */
	id: string,
	/**  "eventkit" or "google". */
	source: string,
	/**  Display label (the account email for Google; NULL for the local source). */
	email: string | null,
	enabled: boolean,
	/**  JSON array of excluded calendar ids, scoped to this account. */
	excluded_calendar_ids: string | null,
	/**  "reauth_required" when the token is dead; NULL means healthy. */
	status: string | null,
	created_at: string,
	/**
	 *  Cached JSON array of the account's calendars (`Vec<CalendarInfo>`), so the
	 *  settings page renders without a live Google call. NULL until first fetched;
	 *  refreshed on connect and on an explicit manual refresh.
	 */
	calendars_json: string | null,
};

/**
 *  Read access state for the local calendar, mirroring `EKAuthorizationStatus`.
 *  `WriteOnly` is treated as insufficient (same as `Denied`) - we only read.
 */
export type CalendarAuthStatus = "notdetermined" | "restricted" | "denied" | "writeonly" | "granted";

/**
 *  Snapshot of the calendar event a recording was matched to, taken at record
 *  time. 1:1 with a meeting. Emails are never stored (see migration / plan).
 */
export type CalendarEvent = {
	meeting_id: string,
	/**  EventKit series identifier (shared across recurring occurrences). */
	event_identifier: string | null,
	/**  Occurrence start (RFC3339) that disambiguates a recurring instance. */
	occurrence_start: string | null,
	title: string | null,
	start_time: string | null,
	end_time: string | null,
	/**  Organizer display name only - never an email address. */
	organizer_name: string | null,
	/**  JSON array of `{name, status}` - names only, never emails. */
	attendees_json: string | null,
	location: string | null,
	conference_url: string | null,
	/**  Event notes/agenda, secret-scrubbed and length-capped before storage. */
	notes: string | null,
	calendar_name: string | null,
	/**  Origin of the snapshot: "eventkit" or "google". */
	source: string,
	/**  Which calendar account won dedup (e.g. "eventkit-local" or a Google sub). */
	account_id: string | null,
	/**  Cross-system event UID (EventKit external id / Google iCalUID). */
	ical_uid: string | null,
	/**  How the event was matched: "high", "low", or "manual". */
	match_confidence: string,
	created_at: string,
};

/**  A calendar the user can include or exclude from matching. */
export type CalendarInfo = {
	id: string,
	title: string,
	/**  True for noise calendars (subscriptions, birthdays) excluded by default. */
	excluded_by_default: boolean,
};

/**
 *  Custom OpenAI-compatible endpoint configuration
 *  Stored as JSON in the database and used for connecting to any OpenAI-compatible API server
 */
export type CustomOpenAIConfig = {
	/**  Base URL of the OpenAI-compatible API endpoint (e.g., "http://localhost:8000/v1") */
	endpoint: string,
	/**  API key for authentication (optional if server doesn't require it) */
	apiKey: string | null,
	/**  Model identifier to use (e.g., "gpt-4", "llama-3-70b", "mistral-7b") */
	model: string,
	/**  Maximum tokens for completion (optional) */
	maxTokens: number | null,
	/**  Temperature parameter (0.0-2.0, optional) */
	temperature: number | null,
	/**  Top-P sampling parameter (0.0-1.0, optional) */
	topP: number | null,
};

export type DatabaseCheckResult = {
	exists: boolean,
	size: number,
};

/**  Response structure for device events */
export type DeviceEventResponse = { type: "DeviceDisconnected"; device_name: string; device_type: string } | { type: "DeviceReconnected"; device_name: string; device_type: string } | { type: "DeviceListChanged" };

export type DeviceType = "Input" | "Output";

/**
 *  A reusable dictation cleanup instruction. At most one preset is active at a
 *  time; the active preset's `prompt` drives the cleanup pass before injection.
 */
export type DictationCleanupPreset = {
	id: string,
	name: string,
	prompt: string,
	is_active: boolean,
	created_at: string,
};

/**  Information about a disconnected device */
export type DisconnectedDeviceInfo = {
	name: string,
	device_type: string,
};

/**
 *  A single stack frame in an exception report. Mirrors the subset of PostHog's
 *  frame schema we populate. `filename`/`function` are code locations, not user
 *  data; the potentially-sensitive part (the message) is redacted separately.
 */
export type ExceptionFrame = {
	filename: string | null,
	function: string | null,
	lineno: number | null,
	colno: number | null,
};

/**
 *  An exception forwarded from the frontend (unhandled errors / promise
 *  rejections). Bundled into one argument; the message is redacted Rust-side.
 */
export type ExceptionReport = {
	exceptionType: string,
	message: string,
	frames?: ExceptionFrame[],
	handled: boolean,
	source: string,
};

export type Folder = {
	id: string,
	name: string,
	emoji: string | null,
	created_at: string,
};

/**  Groq model information returned to frontend */
export type GroqModel = {
	id: string,
	owned_by: string | null,
};

/**  Response when import is started */
export type ImportStarted = {
	message: string,
};

export type Meeting = Meeting_Serialize | Meeting_Deserialize;

export type MeetingDetails = MeetingDetails_Serialize | MeetingDetails_Deserialize;

export type MeetingDetails_Deserialize = {
	id: string,
	title: string,
	created_at: string,
	updated_at: string,
	transcripts: MeetingTranscript_Deserialize[],
};

export type MeetingDetails_Serialize = {
	id: string,
	title: string,
	created_at: string,
	updated_at: string,
	transcripts: MeetingTranscript_Serialize[],
};

/**
 *  Metrics for a completed meeting. Bundled into one argument because Specta
 *  commands accept at most 10 parameters.
 */
export type MeetingEndedMetrics = {
	transcription_provider: string,
	transcription_model: string,
	summary_provider: string,
	summary_model: string,
	total_duration_seconds: number | null,
	active_duration_seconds: number | null,
	pause_duration_seconds: number | null,
	microphone_device_type: string,
	system_audio_device_type: string,
	chunks_processed: number,
	transcript_segments_count: number,
	had_fatal_error: boolean,
};

/**  Meeting metadata without transcripts (for pagination) */
export type MeetingMetadata = MeetingMetadata_Serialize | MeetingMetadata_Deserialize;

/**  Meeting metadata without transcripts (for pagination) */
export type MeetingMetadata_Deserialize = {
	id: string,
	title: string,
	created_at: string,
	updated_at: string,
	folder_path: string | null,
};

/**  Meeting metadata without transcripts (for pagination) */
export type MeetingMetadata_Serialize = {
	id: string,
	title: string,
	created_at: string,
	updated_at: string,
	folder_path?: string | null,
};

export type MeetingTranscript = MeetingTranscript_Serialize | MeetingTranscript_Deserialize;

export type MeetingTranscript_Deserialize = {
	id: string,
	text: string,
	timestamp: string,
	audio_start_time: number | null,
	audio_end_time: number | null,
	duration: number | null,
	/**  Audio source: "mic" (the user) or "system" (other participants) */
	speaker: string | null,
	speaker_id: number | null,
};

export type MeetingTranscript_Serialize = {
	id: string,
	text: string,
	timestamp: string,
	audio_start_time?: number | null,
	audio_end_time?: number | null,
	duration?: number | null,
	/**  Audio source: "mic" (the user) or "system" (other participants) */
	speaker?: string | null,
	speaker_id?: number | null,
};

export type Meeting_Deserialize = {
	id: string,
	title: string,
	created_at: string,
	/**  Organizing folder id (NULL = uncategorized). */
	folder_id: string | null,
};

export type Meeting_Serialize = {
	id: string,
	title: string,
	created_at: string,
	/**  Organizing folder id (NULL = uncategorized). */
	folder_id?: string | null,
};

export type ModelConfig = {
	provider: string,
	model: string,
	whisperModel: string,
	apiKey: string | null,
	ollamaEndpoint: string | null,
};

export type ModelStatus = {
	parakeet: string,
	summary: string,
};

export type NotesResponse = NotesResponse_Serialize | NotesResponse_Deserialize;

export type NotesResponse_Deserialize = {
	meeting_id: string,
	notes_markdown: string | null,
	summary_context: string | null,
};

export type NotesResponse_Serialize = {
	meeting_id: string,
	notes_markdown?: string | null,
	summary_context?: string | null,
};

export type Notification = {
	id: string | null,
	title: string,
	body: string,
	notification_type: NotificationType,
	priority: NotificationPriority,
	timeout: NotificationTimeout,
	icon: string | null,
	sound: boolean,
	actions: NotificationAction[],
};

export type NotificationAction = {
	id: string,
	title: string,
	action_type: NotificationActionType,
};

export type NotificationActionType = "Button" | "Reply";

export type NotificationPreferences = {
	/**  Show recording started notifications */
	show_recording_started: boolean,
	/**  Show recording stopped notifications */
	show_recording_stopped: boolean,
	/**  Show recording paused notifications */
	show_recording_paused: boolean,
	/**  Show recording resumed notifications */
	show_recording_resumed: boolean,
	/**  Show transcription complete notifications */
	show_transcription_complete: boolean,
	/**  Show meeting reminder notifications */
	show_meeting_reminders: boolean,
	/**  Show system error notifications */
	show_system_errors: boolean,
	/**  Minutes before meeting to show reminder (0 = disabled) */
	meeting_reminder_minutes: number[],
};

export type NotificationPriority = "Low" | "Normal" | "High" | "Critical";

export type NotificationSettings = {
	/**  Enable recording lifecycle notifications (start/stop/pause/resume) */
	recording_notifications: boolean,
	/**  Enable time-based meeting reminders */
	time_based_reminders: boolean,
	/**  Enable meeting reminders based on calendar events */
	meeting_reminders: boolean,
	/**  Respect system Do Not Disturb settings */
	respect_do_not_disturb: boolean,
	/**  Enable notification sounds */
	notification_sound: boolean,
	/**  System notification permission has been granted */
	system_permission_granted: boolean,
	/**  User has completed the initial notification setup */
	consent_given: boolean,
	/**  Manual DND mode (user-controlled) */
	manual_dnd_mode: boolean,
	/**  Notification preferences for different types */
	notification_preferences: NotificationPreferences,
};

export type NotificationTimeout = "Never" | { Seconds: number } | "Default";

export type NotificationType = "RecordingStarted" | "RecordingStopped" | "RecordingPaused" | "RecordingResumed" | "TranscriptionComplete" | ({ MeetingReminder: number }) & { SystemError?: never } | ({ SystemError: string }) & { MeetingReminder?: never } | "Test";

export type OllamaModel = {
	name: string,
	id: string,
	size: string,
	modified: string,
};

export type OnboardingStatus = {
	version: string,
	completed: boolean,
	current_step: number,
	model_status: ModelStatus,
	last_updated: string,
};

/**  OpenAI model information returned to frontend */
export type OpenAIModel = {
	id: string,
};

export type OpenRouterModel = {
	id: string,
	name: string,
	context_length: number | null,
	prompt_price: string | null,
	completion_price: string | null,
};

/**  Paginated transcripts response with total count */
export type PaginatedTranscriptsResponse = PaginatedTranscriptsResponse_Serialize | PaginatedTranscriptsResponse_Deserialize;

/**  Paginated transcripts response with total count */
export type PaginatedTranscriptsResponse_Deserialize = {
	transcripts: MeetingTranscript_Deserialize[],
	total_count: number,
	has_more: boolean,
};

/**  Paginated transcripts response with total count */
export type PaginatedTranscriptsResponse_Serialize = {
	transcripts: MeetingTranscript_Serialize[],
	total_count: number,
	has_more: boolean,
};

/**  Information about a Parakeet model */
export type ParakeetModelInfo = {
	name: string,
	path: string,
	size_mb: number,
	quantization: QuantizationType,
	speed: string,
	status: any,
	description: string,
};

/**
 *  A lightweight event for the settings "upcoming events" preview, so the user
 *  can confirm a source is being read. Attendee names/notes are not included.
 */
export type PreviewEvent = {
	title: string,
	start: string,
	/**  RFC3339 end, when known — bounds the home "Start" button's actionable window. */
	end: string | null,
	source: string,
	calendar_name: string | null,
	/**  Series/occurrence identity for pre-assign-to-folder and the scheduler. */
	ical_uid: string | null,
	/**
	 *  `minute_bucket(start)` — the stable per-occurrence key shared with the rules
	 *  table and the scheduler.
	 */
	occurrence_minute: number,
	/**  Part of a recurring series — gates the "Auto-add future meetings?" prompt. */
	is_recurring: boolean,
	/**  Parsed conference/meeting URL (Zoom/Meet/Teams/…), when present. */
	conference_url: string | null,
};

/**
 *  Processes transcript and generates summary (Native SQLx implementation)
 * 
 *  Spawns a background task and returns immediately with process_id
 *  Parameters for processing a transcript into a summary. Bundled into one
 *  argument because Specta commands accept at most 10 parameters.
 */
export type ProcessTranscriptParams = {
	text: string,
	model: string,
	modelName: string,
	meetingId: string | null,
	chunkSize: number | null,
	overlap: number | null,
	customPrompt: string | null,
	templateId: string | null,
	summaryLanguage: string | null,
	authToken: string | null,
};

export type ProcessTranscriptResponse = {
	message: string,
	process_id: string,
};

/**  Quantization type for Parakeet models */
export type QuantizationType = "FP32" | "Int8";

/**  Reconnection status information */
export type ReconnectionStatus = {
	is_reconnecting: boolean,
	disconnected_device: DisconnectedDeviceInfo | null,
};

export type RecordingArgs = {
	save_path: string,
};

export type RecordingPreferences = {
	save_folder: string,
	auto_save: boolean,
	file_format: string,
	preferred_mic_device?: string | null,
	preferred_system_device?: string | null,
	system_audio_backend?: string | null,
};

/**  Response when retranscription is started */
export type RetranscriptionStarted = {
	meeting_id: string,
	message: string,
};

export type SummaryLanguageDetection = {
	language: string | null,
	reason: SummaryLanguageDetectionReason,
};

export type SummaryLanguageDetectionReason = "detected" | "tie" | "low_confidence" | "unsupported" | "empty";

/**  Model information for UI display */
export type SummaryModelInfo = {
	/**  Model name (e.g., "gemma3:1b") */
	name: string,
	/**  Display name for UI */
	display_name: string,
	/**  Current status */
	status: any,
	/**  File path (if available) */
	path: string,
	/**  Size in MB */
	size_mb: number,
	/**  Context window size in tokens */
	context_size: number,
	/**  Description */
	description: string,
	/**  GGUF filename on disk */
	gguf_file: string,
};

export type SummaryResponse = {
	status: string,
	meetingName: string | null,
	meeting_id: string,
	start: string | null,
	end: string | null,
	data: any | null,
	error: string | null,
};

/**  Detailed template structure for preview/debugging */
export type TemplateDetails = {
	/**  Template identifier */
	id: string,
	/**  Display name */
	name: string,
	/**  Description */
	description: string,
	/**  List of section titles in order */
	sections: string[],
};

/**  Template metadata for UI display */
export type TemplateInfo = {
	/**  Template identifier (e.g., "daily_standup", "standard_meeting") */
	id: string,
	/**  Display name for the template */
	name: string,
	/**  Brief description of the template's purpose */
	description: string,
};

export type TranscriptConfig = {
	provider: string,
	model: string,
	apiKey: string | null,
};

export type TranscriptSearchResult = {
	id: string,
	title: string,
	matchContext: string,
	timestamp: string,
};

/**  Structured transcript segment for JSON export */
export type TranscriptSegment = {
	id: string,
	text: string,
	audio_start_time: number | null,
	audio_end_time: number | null,
	duration: number | null,
	display_time: string,
	confidence: number | null,
	sequence_id: number,
	/**  Audio source: "mic" (the user) or "system" (other participants) */
	speaker?: string | null,
};

export type TranscriptionStatus = {
	chunks_in_queue: number,
	is_processing: boolean,
	last_activity_ms: number,
};

export type VocabularyEntry = {
	/**  The text the engine tends to produce (matched case-insensitively). */
	from: string,
	/**  The correct replacement (inserted verbatim). */
	to: string,
};

export type WhisperModelInfo = {
	name: string,
	path: string,
	size_mb: number,
	accuracy: string,
	speed: string,
	status: any,
	description: string,
};

/**  xAI model information returned to frontend */
export type XaiModel = {
	id: string,
	owned_by: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

